name: autoshot
version: 1.4.0
description:
  Automate App Store and Play Store screenshot generation across multiple
  devices, locales, and screens with web download and mobile file export.
homepage: https://github.com/andronasef/autoshot
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  device_preview: ^1.3.1
  flutter:
    sdk: flutter

  provider: ^6.1.2
  archive: ^4.0.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
