name: autoshot
version: 1.1.0
description:
  Automate App Store and Play Store screenshot generation across multiple
  devices, locales, and screens. Runs in Flutter Web and outputs a ZIP archive.
homepage: https://github.com/andronasef/autoshot
environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  device_preview: ^1.3.1
  flutter:
    sdk: flutter
  provider: ^6.1.2
  archive: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
